# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1TirdENGxOB2TxmDXJuKGpadvbsObTe
"""

itens = []
def main():
    while True:
        print("\nMenu:")
        print("1. Adicionar item")
        print("2. Listar itens")
        print("3. Marcar item como comprado")
        print("4. Remover item")
        print("5. Sair")
        opc = int(input("Escolha: "))

        if opc == 1:
            adicionar_item()
        elif opc == 2:
            listar_items()
        elif opc == 3:
            marcar_comprado()
        elif opc == 4:
            remover_item()
        elif opc == 5:
            break
        else:
            print("Opção inválida!")

def adicionar_item():
    nome = input("Insira o nome do item: ")
    quantidade = int(input("Insira a quantidade do item: "))
    comprado = False
    itens.append({'nome': nome, 'quantidade': quantidade, 'comprado': comprado})
    print("O item foi adicionado com sucesso!")

def listar_items():
    if not itens:
        print("Nenhum item na lista.")
    else:
        for i, x in enumerate(itens, start=1):
            status = "✔️" if x['comprado'] else "❌"
            print(f"{i}. {x['nome']} - Quantidade: {x['quantidade']} - Comprado: {status}")

def marcar_comprado():
    listar_items()
    indice = int(input("Digite o número do item que deseja marcar como comprado: "))
    if 1 <= indice <= len(itens):
        itens[indice-1]['comprado'] = True
        print("Item marcado como comprado!")
    else:
        print("Número inválido.")

def remover_item():
    listar_items()
    indice = int(input("Digite o número do item que deseja remover: "))
    if 1 <= indice <= len(itens):
        removido = itens.pop(indice-1)
        print(f"Item '{removido['nome']}' removido com sucesso!")
    else:
        print("Número inválido.")

main()

print(itens)