# -*- coding: utf-8 -*-
"""EDA_Tech_Store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V64jOu_q3HWxqVXPV36ZtZ2ag6f3zqLF
"""

import pandas as pd

df = pd.read_csv('vendas.csv')

df.head()

df.info()

total_registros = len(df)
print(f"\n2. Número total de registros: {total_registros}")

df['receita'] = df['quantidade'] * df['preco_unitario']
receita_total = df['receita'].sum()
print(f"\n3. Receita Total: R$ {receita_total:,.2f}")

vendas_eletronicos = df[df['categoria'] == 'Eletrônicos']
print("\n4. Vendas da categoria 'Eletrônicos':")
print(vendas_eletronicos)

vendas_por_produto = df.groupby('produto')['quantidade'].sum()
produto_mais_vendido = vendas_por_produto.idxmax()
qtd_produto_mais_vendido = vendas_por_produto.max()

print(f"\n5. Produto mais vendido (em quantidade):")
print(f"Produto: {produto_mais_vendido} | Quantidade total: {qtd_produto_mais_vendido}")

vendas_por_regiao = df.groupby('regiao')['receita'].sum()
regiao_maior_valor = vendas_por_regiao.idxmax()
valor_maior_regiao = vendas_por_regiao.max()

print(f"\n6. Região com maior valor de compras:")
print(f"Região: {regiao_maior_valor} | Valor total: R$ {valor_maior_regiao:,.2f}")